import { CardData } from "@/interface/recipe";

const DummyData: CardData[] = [
  {
    thumbNailImg: "public/food/indianFood-image_127425-18.avif",
    title: "Indian style chicken",
    id: "wjs2282",
    viewCount: 1,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar1.avif",
  },
  {
    thumbNailImg: "public/food/bibimbab.jpeg",
    title: "Korean Bibimbap that's easy to follow",
    id: "wjs2282",
    viewCount: 12,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar2.png",
  },
  {
    thumbNailImg: "public/food/bugers.jpeg",
    title: "New York Style Homemade Shake Shack Burger",
    id: "wjs2282",
    viewCount: 13,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar3.png",
  },
  {
    thumbNailImg: "public/food/panCake.jpeg",
    title: "Pancake that my dad made for me every Sunday",
    id: "wjs2282",
    viewCount: 14,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar2.png",
  },
  {
    thumbNailImg: "public/food/pork.webp",
    title:
      "A must-win date recipe! Homemade salmon steak with a restaurant vibe",
    id: "wjs2282",
    viewCount: 15,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar1.avif",
  },
  {
    thumbNailImg: "public/food/salad.jpeg",
    title: "Salad Recipe of Memories",
    id: "wjs2282",
    viewCount: 2,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar3.png",
  },
  {
    thumbNailImg: "public/food/cheeseBuger.avif",
    title: "On a day when I'm tired of dieting, a meat bomb burger",
    id: "wjs2282",
    viewCount: 3,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar2.png",
  },
  {
    thumbNailImg: "public/food/cake.jpeg",
    title: "Best Strawberry Cake for Kids",
    id: "wjs2282",
    viewCount: 4,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar1.avif",
  },
  {
    thumbNailImg: "public/Food/shusi.webp",
    title: "A sushi recipe developed by a Japanese sushi chef for 20 years",
    id: "wjs2282",
    viewCount: 5,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar1.avif",
  },
  {
    thumbNailImg: "public/Food/gv40000225004_1.jpg",
    title: "One bowl on a day when you need hot soup! Vietnamese rice noodles",
    id: "wjs2282",
    viewCount: 1,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar3.png",
  },
  {
    thumbNailImg: "public/food/indianFood-image_127425-18.avif",
    title: "Indian style chicken",
    id: "wjs2282",
    viewCount: 2,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar2.png",
  },
  {
    thumbNailImg: "public/food/bibimbab.jpeg",
    title: "Korean Bibimbap that's easy to follow",
    id: "wjs2282",
    viewCount: 2,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar2.png",
  },
  {
    thumbNailImg: "public/food/bugers.jpeg",
    title: "New York Style Homemade Shake Shack Burger",
    id: "wjs2282",
    viewCount: 3,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar1.avif",
  },
  {
    thumbNailImg: "public/food/panCake.jpeg",
    title: "Pancake that my dad made for me every Sunday",
    id: "wjs2282",
    viewCount: 5,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar1.avif",
  },
  {
    thumbNailImg: "public/food/pork.webp",
    title:
      "A must-win date recipe! Homemade salmon steak with a restaurant vibe",
    id: "wjs2282",
    viewCount: 1,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar3.png",
  },
  {
    thumbNailImg: "public/food/salad.jpeg",
    title: "Salad Recipe of Memories",
    id: "wjs2282",
    viewCount: 2,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar2.png",
  },
  {
    thumbNailImg: "public/food/indianFood-image_127425-18.avif",
    title: "Indian style chicken",
    id: "wjs2282",
    viewCount: 1,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar1.avif",
  },
  {
    thumbNailImg: "public/food/bibimbab.jpeg",
    title: "Korean Bibimbap that's easy to follow",
    id: "wjs2282",
    viewCount: 12,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar2.png",
  },
  {
    thumbNailImg: "public/food/bugers.jpeg",
    title: "New York Style Homemade Shake Shack Burger",
    id: "wjs2282",
    viewCount: 13,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar3.png",
  },
  {
    thumbNailImg: "public/food/panCake.jpeg",
    title: "Pancake that my dad made for me every Sunday",
    id: "wjs2282",
    viewCount: 14,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar2.png",
  },
  {
    thumbNailImg: "public/food/pork.webp",
    title:
      "A must-win date recipe! Homemade salmon steak with a restaurant vibe",
    id: "wjs2282",
    viewCount: 15,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar1.avif",
  },
  {
    thumbNailImg: "public/food/salad.jpeg",
    title: "Salad Recipe of Memories",
    id: "wjs2282",
    viewCount: 2,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar3.png",
  },
  {
    thumbNailImg: "public/food/cheeseBuger.avif",
    title: "On a day when I'm tired of dieting, a meat bomb burger",
    id: "wjs2282",
    viewCount: 3,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar2.png",
  },
  {
    thumbNailImg: "public/food/cake.jpeg",
    title: "Best Strawberry Cake for Kids",
    id: "wjs2282",
    viewCount: 4,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar1.avif",
  },
  {
    thumbNailImg: "public/Food/shusi.webp",
    title: "A sushi recipe developed by a Japanese sushi chef for 20 years",
    id: "wjs2282",
    viewCount: 5,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar1.avif",
  },
  {
    thumbNailImg: "public/Food/gv40000225004_1.jpg",
    title: "One bowl on a day when you need hot soup! Vietnamese rice noodles",
    id: "wjs2282",
    viewCount: 1,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar3.png",
  },
  {
    thumbNailImg: "public/food/indianFood-image_127425-18.avif",
    title: "Indian style chicken",
    id: "wjs2282",
    viewCount: 2,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar2.png",
  },
  {
    thumbNailImg: "public/food/bibimbab.jpeg",
    title: "Korean Bibimbap that's easy to follow",
    id: "wjs2282",
    viewCount: 2,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar2.png",
  },
  {
    thumbNailImg: "public/food/bugers.jpeg",
    title: "New York Style Homemade Shake Shack Burger",
    id: "wjs2282",
    viewCount: 3,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar1.avif",
  },
  {
    thumbNailImg: "public/food/indianFood-image_127425-18.avif",
    title: "Indian style chicken",
    id: "wjs2282",
    viewCount: 1,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar1.avif",
  },
  {
    thumbNailImg: "public/food/bibimbab.jpeg",
    title: "Korean Bibimbap that's easy to follow",
    id: "wjs2282",
    viewCount: 12,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar2.png",
  },
  {
    thumbNailImg: "public/food/bugers.jpeg",
    title: "New York Style Homemade Shake Shack Burger",
    id: "wjs2282",
    viewCount: 13,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar3.png",
  },
  {
    thumbNailImg: "public/food/panCake.jpeg",
    title: "Pancake that my dad made for me every Sunday",
    id: "wjs2282",
    viewCount: 14,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar2.png",
  },
  {
    thumbNailImg: "public/food/pork.webp",
    title:
      "A must-win date recipe! Homemade salmon steak with a restaurant vibe",
    id: "wjs2282",
    viewCount: 15,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar1.avif",
  },
  {
    thumbNailImg: "public/food/salad.jpeg",
    title: "Salad Recipe of Memories",
    id: "wjs2282",
    viewCount: 2,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar3.png",
  },
  {
    thumbNailImg: "public/food/cheeseBuger.avif",
    title: "On a day when I'm tired of dieting, a meat bomb burger",
    id: "wjs2282",
    viewCount: 3,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar2.png",
  },
  {
    thumbNailImg: "public/food/cake.jpeg",
    title: "Best Strawberry Cake for Kids",
    id: "wjs2282",
    viewCount: 4,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar1.avif",
  },
  {
    thumbNailImg: "public/Food/shusi.webp",
    title: "A sushi recipe developed by a Japanese sushi chef for 20 years",
    id: "wjs2282",
    viewCount: 5,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar1.avif",
  },
  {
    thumbNailImg: "public/Food/gv40000225004_1.jpg",
    title: "One bowl on a day when you need hot soup! Vietnamese rice noodles",
    id: "wjs2282",
    viewCount: 1,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar3.png",
  },
  {
    thumbNailImg: "public/food/indianFood-image_127425-18.avif",
    title: "Indian style chicken",
    id: "wjs2282",
    viewCount: 2,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar2.png",
  },
  {
    thumbNailImg: "public/food/bibimbab.jpeg",
    title: "Korean Bibimbap that's easy to follow",
    id: "wjs2282",
    viewCount: 2,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar2.png",
  },
  {
    thumbNailImg: "public/food/bugers.jpeg",
    title: "New York Style Homemade Shake Shack Burger",
    id: "wjs2282",
    viewCount: 3,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar1.avif",
  },
  {
    thumbNailImg: "public/food/indianFood-image_127425-18.avif",
    title: "Indian style chicken",
    id: "wjs2282",
    viewCount: 1,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar1.avif",
  },
  {
    thumbNailImg: "public/food/bibimbab.jpeg",
    title: "Korean Bibimbap that's easy to follow",
    id: "wjs2282",
    viewCount: 12,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar2.png",
  },
  {
    thumbNailImg: "public/food/bugers.jpeg",
    title: "New York Style Homemade Shake Shack Burger",
    id: "wjs2282",
    viewCount: 13,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar3.png",
  },
  {
    thumbNailImg: "public/food/panCake.jpeg",
    title: "Pancake that my dad made for me every Sunday",
    id: "wjs2282",
    viewCount: 14,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar2.png",
  },
  {
    thumbNailImg: "public/food/pork.webp",
    title:
      "A must-win date recipe! Homemade salmon steak with a restaurant vibe",
    id: "wjs2282",
    viewCount: 15,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar1.avif",
  },
  {
    thumbNailImg: "public/food/salad.jpeg",
    title: "Salad Recipe of Memories",
    id: "wjs2282",
    viewCount: 2,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar3.png",
  },
  {
    thumbNailImg: "public/food/cheeseBuger.avif",
    title: "On a day when I'm tired of dieting, a meat bomb burger",
    id: "wjs2282",
    viewCount: 3,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar2.png",
  },
  {
    thumbNailImg: "public/food/cake.jpeg",
    title: "Best Strawberry Cake for Kids",
    id: "wjs2282",
    viewCount: 4,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar1.avif",
  },
  {
    thumbNailImg: "public/Food/shusi.webp",
    title: "A sushi recipe developed by a Japanese sushi chef for 20 years",
    id: "wjs2282",
    viewCount: 5,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar1.avif",
  },
  {
    thumbNailImg: "public/Food/gv40000225004_1.jpg",
    title: "One bowl on a day when you need hot soup! Vietnamese rice noodles",
    id: "wjs2282",
    viewCount: 1,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar3.png",
  },
  {
    thumbNailImg: "public/food/indianFood-image_127425-18.avif",
    title: "Indian style chicken",
    id: "wjs2282",
    viewCount: 2,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar2.png",
  },
  {
    thumbNailImg: "public/food/bibimbab.jpeg",
    title: "Korean Bibimbap that's easy to follow",
    id: "wjs2282",
    viewCount: 2,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar2.png",
  },
  {
    thumbNailImg: "public/food/bugers.jpeg",
    title: "New York Style Homemade Shake Shack Burger",
    id: "wjs2282",
    viewCount: 3,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar1.avif",
  },
  {
    thumbNailImg: "public/food/panCake.jpeg",
    title: "Pancake that my dad made for me every Sunday",
    id: "wjs2282",
    viewCount: 5,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar1.avif",
  },
  {
    thumbNailImg: "public/food/pork.webp",
    title:
      "A must-win date recipe! Homemade salmon steak with a restaurant vibe",
    id: "wjs2282",
    viewCount: 1,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar3.png",
  },
  {
    thumbNailImg: "public/food/salad.jpeg",
    title: "Salad Recipe of Memories",
    id: "wjs2282",
    viewCount: 2,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar2.png",
  },
  {
    thumbNailImg: "public/food/indianFood-image_127425-18.avif",
    title: "Indian style chicken",
    id: "wjs2282",
    viewCount: 1,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar1.avif",
  },
  {
    thumbNailImg: "public/food/bibimbab.jpeg",
    title: "Korean Bibimbap that's easy to follow",
    id: "wjs2282",
    viewCount: 12,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar2.png",
  },
  {
    thumbNailImg: "public/food/bugers.jpeg",
    title: "New York Style Homemade Shake Shack Burger",
    id: "wjs2282",
    viewCount: 13,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar3.png",
  },
  {
    thumbNailImg: "public/food/panCake.jpeg",
    title: "Pancake that my dad made for me every Sunday",
    id: "wjs2282",
    viewCount: 14,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar2.png",
  },
  {
    thumbNailImg: "public/food/pork.webp",
    title:
      "A must-win date recipe! Homemade salmon steak with a restaurant vibe",
    id: "wjs2282",
    viewCount: 15,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar1.avif",
  },
  {
    thumbNailImg: "public/food/salad.jpeg",
    title: "Salad Recipe of Memories",
    id: "wjs2282",
    viewCount: 2,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar3.png",
  },
  {
    thumbNailImg: "public/food/cheeseBuger.avif",
    title: "On a day when I'm tired of dieting, a meat bomb burger",
    id: "wjs2282",
    viewCount: 3,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar2.png",
  },
  {
    thumbNailImg: "public/food/cake.jpeg",
    title: "Best Strawberry Cake for Kids",
    id: "wjs2282",
    viewCount: 4,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar1.avif",
  },
  {
    thumbNailImg: "public/Food/shusi.webp",
    title: "A sushi recipe developed by a Japanese sushi chef for 20 years",
    id: "wjs2282",
    viewCount: 5,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar1.avif",
  },
  {
    thumbNailImg: "public/Food/gv40000225004_1.jpg",
    title: "One bowl on a day when you need hot soup! Vietnamese rice noodles",
    id: "wjs2282",
    viewCount: 1,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar3.png",
  },
  {
    thumbNailImg: "public/food/indianFood-image_127425-18.avif",
    title: "Indian style chicken",
    id: "wjs2282",
    viewCount: 2,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar2.png",
  },
  {
    thumbNailImg: "public/food/bibimbab.jpeg",
    title: "Korean Bibimbap that's easy to follow",
    id: "wjs2282",
    viewCount: 2,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar2.png",
  },
  {
    thumbNailImg: "public/food/bugers.jpeg",
    title: "New York Style Homemade Shake Shack Burger",
    id: "wjs2282",
    viewCount: 3,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar1.avif",
  },
  {
    thumbNailImg: "public/food/indianFood-image_127425-18.avif",
    title: "Indian style chicken",
    id: "wjs2282",
    viewCount: 1,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar1.avif",
  },
  {
    thumbNailImg: "public/food/bibimbab.jpeg",
    title: "Korean Bibimbap that's easy to follow",
    id: "wjs2282",
    viewCount: 12,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar2.png",
  },
  {
    thumbNailImg: "public/food/bugers.jpeg",
    title: "New York Style Homemade Shake Shack Burger",
    id: "wjs2282",
    viewCount: 13,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar3.png",
  },
  {
    thumbNailImg: "public/food/panCake.jpeg",
    title: "Pancake that my dad made for me every Sunday",
    id: "wjs2282",
    viewCount: 14,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar2.png",
  },
  {
    thumbNailImg: "public/food/pork.webp",
    title:
      "A must-win date recipe! Homemade salmon steak with a restaurant vibe",
    id: "wjs2282",
    viewCount: 15,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar1.avif",
  },
  {
    thumbNailImg: "public/food/salad.jpeg",
    title: "Salad Recipe of Memories",
    id: "wjs2282",
    viewCount: 2,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar3.png",
  },
  {
    thumbNailImg: "public/food/cheeseBuger.avif",
    title: "On a day when I'm tired of dieting, a meat bomb burger",
    id: "wjs2282",
    viewCount: 3,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar2.png",
  },
  {
    thumbNailImg: "public/food/cake.jpeg",
    title: "Best Strawberry Cake for Kids",
    id: "wjs2282",
    viewCount: 4,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar1.avif",
  },
  {
    thumbNailImg: "public/Food/shusi.webp",
    title: "A sushi recipe developed by a Japanese sushi chef for 20 years",
    id: "wjs2282",
    viewCount: 5,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar1.avif",
  },
  {
    thumbNailImg: "public/Food/gv40000225004_1.jpg",
    title: "One bowl on a day when you need hot soup! Vietnamese rice noodles",
    id: "wjs2282",
    viewCount: 1,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar3.png",
  },
  {
    thumbNailImg: "public/food/indianFood-image_127425-18.avif",
    title: "Indian style chicken",
    id: "wjs2282",
    viewCount: 2,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar2.png",
  },
  {
    thumbNailImg: "public/food/bibimbab.jpeg",
    title: "Korean Bibimbap that's easy to follow",
    id: "wjs2282",
    viewCount: 2,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar2.png",
  },
  {
    thumbNailImg: "public/food/bugers.jpeg",
    title: "New York Style Homemade Shake Shack Burger",
    id: "wjs2282",
    viewCount: 3,
    date: "2023-06-10",
    avatarImg: "public/Avatar/avatar1.avif",
  },
];
export default DummyData;
