import { CardData } from "@/interface/recipe";
const DummyData: CardData[] = [
  {
    img: "public/indianFood-image_127425-18.avif",
    title: "Indian style chicken",
    id: "wjs2282",
    viewCount: 1,
    date: "2023-06-10",
  },
  {
    img: "public/bibimbab.jpeg",
    title: "Korean Bibimbap that's easy to follow",
    id: "wjs2282",
    viewCount: 12,
    date: "2023-06-10",
  },
  {
    img: "public/bugers.jpeg",
    title: "New York Style Homemade Shake Shack Burger",
    id: "wjs2282",
    viewCount: 13,
    date: "2023-06-10",
  },
  {
    img: "public/panCake.jpeg",
    title: "Pancake that my dad made for me every Sunday",
    id: "wjs2282",
    viewCount: 14,
    date: "2023-06-10",
  },
  {
    img: "public/pork.webp",
    title:
      "A must-win date recipe! Homemade salmon steak with a restaurant vibe",
    id: "wjs2282",
    viewCount: 15,
    date: "2023-06-10",
  },
  {
    img: "public/salad.jpeg",
    title: "Salad Recipe of Memories",
    id: "wjs2282",
    viewCount: 2,
    date: "2023-06-10",
  },
  {
    img: "public/cheeseBuger.avif",
    title: "레시피 제목",
    id: "wjs2282",
    viewCount: 3,
    date: "2023-06-10",
  },
  {
    img: "public/cake.jpeg",
    title: "레시피 제목",
    id: "wjs2282",
    viewCount: 4,
    date: "2023-06-10",
  },
  {
    img: "../../public/11.png",
    title: "레시피 제목",
    id: "wjs2282",
    viewCount: 5,
    date: "2023-06-10",
  },
  {
    img: "../../public/11.png",
    title: "레시피 제목",
    id: "wjs2282",
    viewCount: 1,
    date: "2023-06-10",
  },
  {
    img: "public/indianFood-image_127425-18.avif",
    title: "Indian style chicken",
    id: "wjs2282",
    viewCount: 2,
    date: "2023-06-10",
  },
  {
    img: "public/bibimbab.jpeg",
    title: "Korean Bibimbap that's easy to follow",
    id: "wjs2282",
    viewCount: 2,
    date: "2023-06-10",
  },
  {
    img: "public/bugers.jpeg",
    title: "New York Style Homemade Shake Shack Burger",
    id: "wjs2282",
    viewCount: 3,
    date: "2023-06-10",
  },
  {
    img: "public/panCake.jpeg",
    title: "Pancake that my dad made for me every Sunday",
    id: "wjs2282",
    viewCount: 5,
    date: "2023-06-10",
  },
  {
    img: "public/pork.webp",
    title:
      "A must-win date recipe! Homemade salmon steak with a restaurant vibe",
    id: "wjs2282",
    viewCount: 1,
    date: "2023-06-10",
  },
  {
    img: "public/salad.jpeg",
    title: "Salad Recipe of Memories",
    id: "wjs2282",
    viewCount: 2,
    date: "2023-06-10",
  },
  {
    img: "public/cheeseBuger.avif",
    title: "레시피 제목",
    id: "wjs2282",
    viewCount: 1,
    date: "2023-06-10",
  },
  {
    img: "public/cake.jpeg",
    title: "레시피 제목",
    id: "wjs2282",
    viewCount: 3,
    date: "2023-06-10",
  },
  {
    img: "../../public/11.png",
    title: "레시피 제목",
    id: "wjs2282",
    viewCount: 5,
    date: "2023-06-10",
  },
  {
    img: "../../public/11.png",
    title: "레시피 제목",
    id: "wjs2282",
    viewCount: 2,
    date: "2023-06-10",
  },
];
export default DummyData;
